name: Sync Fork

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.github/workflows/sync.yml'
  repository_dispatch: 
    types: [sync-trigger]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          repository: swp91/The-julge-fork
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set Git Config
        run: |
          git config --global user.email "seongwoo4477@gmail.com"
          git config --global user.name "swp91"

      - name: Add Upstream
        run: git remote add upstream https://github.com/codeit-frontend-part3-team3/The-julge.git

      - name: Fetch Upstream Branches
        run: git fetch upstream

      - name: Sync Branches
        run: |
          for branch in main develop; do
            git checkout $branch || git checkout -b $branch
            git reset --hard upstream/$branch
            git push origin $branch --force
          done
